### ISSUE TITLE
Download error.

### ISSUE THREAD

**Issue by dingdingJ** [johnrosen1/vpstoolbox#101]
刚开始安装即出现红字提示：

Download error.
Install acme.sh fail,please check your internet availability!!!

**Comment by dingdingJ** [comment]
Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6

**Comment by johnrosen1** [comment]
@dingdingJ 你安装acme.sh失败了，看起来你的dns有问题，请自行检查

**Comment by johnrosen1** [comment]
https://github.com/johnrosen1/vpstoolbox/commit/c549fb2a4408252d4cab5593cb3cf07f49cd91f8 @dingdingJ  这样应该就行了

**Comment by dingdingJ** [comment]
重登录 SSH 后，如何重新显示结果？

**Comment by johnrosen1** [comment]
@dingdingJ bash /etc/profile.d/mymotd.sh

**Comment by dingdingJ** [comment]
奇怪了。
比如我的网站是 https://xxxxx.monster/_XQgDC3yNZ8V.q/
访问后提示：Cannot GET /_XQgDC3yNZ8V.q/

**Comment by johnrosen1** [comment]
@dingdingJ 你的密码可能设置的太复杂了

**Comment by dingdingJ** [comment]
好吧，，，重装，谢谢大佬。。

**Comment by johnrosen1** [comment]
@dingdingJ 问题不大

**Comment by dingdingJ** [comment]
注册 Trojan 面板第一个用户时，总是显示500错误。不知问题在哪？

**Comment by johnrosen1** [comment]
@dingdingJ 不清楚，这个功能我平时不用，你自己试试吧

**Comment by johnrosen1** [comment]
closed
