### ISSUE TITLE
Nodejs 8.10.0 安装HEXO会有问题

### ISSUE THREAD

**Issue by fudingyu** [johnrosen1/vpstoolbox#104]
hexo init hexo
console.js:35 throw new typeerror('console expects a writable stream instance'

官方解决方案。
https://github.com/nodejs/node/issues/21366

**Comment by johnrosen1** [comment]
@fudingyu 你无需自行安装nodejs,脚本会自动安装的

**Comment by johnrosen1** [comment]
closed
