### ISSUE TITLE
证书过期

### ISSUE THREAD

**Issue by pkumza** [johnrosen1/vpstoolbox#105]
**Is it really a bug?Please try to solve it by yourself first.（无论这是否是一个Bug,请先尝试自行解决！）**
尝试了1小时未果
**Non-related topics will be marked as spam and be closed immediately!（所有与本项目无关的话题都将被视为spam并被立即关闭！）**

**请勿使用Vultr运行本项目,vultr导致的一切错误,本项目不负责！！！**

**Describe the bug**

**To Reproduce**

**Expected behavior**

希望证书自动续期，
设置 API 了，开心用了3个月，一旦过期又得重新搭建一遍。

**Screenshots**

**Additional context**

**Comment by johnrosen1** [comment]
@pkumza 最新版已设置自动续期

**Comment by pkumza** [comment]
感谢。
那我先 close 了，不确定三个月后会不会 reopen (手动狗头)

**Comment by bogo-y** [comment]
同样遇到了这个问题 已经用最新版重装了

**Comment by pkumza** [comment]
覆盖安装了。
提示说是安装成功，但是日志里面：
```
12月 03 18:24:19 我的域名 systemd[1]: Started trojan.
12月 03 18:24:19 我的域名 systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
12月 03 18:24:19 我的域名 trojan[13535]: Welcome to trojan 1.16.0
12月 03 18:24:19 我的域名 trojan[13535]: [2020-12-03 18:24:19] [FATAL] fatal: use_private_key_file: No such file or directory
12月 03 18:24:19 我的域名 trojan[13535]: [2020-12-03 18:24:19] [FATAL] exiting. . .
12月 03 18:24:19 我的域名 systemd[1]: trojan.service: Failed with result 'exit-code'.
12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Service RestartSec=1s expired, scheduling restart.
12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Scheduled restart job, restart counter is at 5.
12月 03 18:24:20 我的域名 systemd[1]: Stopped trojan.
12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Start request repeated too quickly.
12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Failed with result 'exit-code'.
12月 03 18:24:20 我的域名 systemd[1]: Failed to start trojan.
```

**Comment by knightelessar** [comment]
> 12月 03 18:24:19 我的域名 systemd[1]: Started trojan.
> 12月 03 18:24:19 我的域名 systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
> 12月 03 18:24:19 我的域名 trojan[13535]: Welcome to trojan 1.16.0
> 12月 03 18:24:19 我的域名 trojan[13535]: [2020-12-03 18:24:19] [FATAL] fatal: use_private_key_file: No such file or directory

今天第一次安装。证书申请的时候没有看到log里报错，这个`fatal: use_private_key_file: No such file or directory`是新的issue吧。

**Comment by johnrosen1** [comment]
@pkumza 进群说，这里回复慢

**Comment by fudingyu** [comment]
我也有这个问题

**Comment by fudingyu** [comment]
> 覆盖安装了。
> 提示说是安装成功，但是日志里面：
> 
> ```
> 12月 03 18:24:19 我的域名 systemd[1]: Started trojan.
> 12月 03 18:24:19 我的域名 systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
> 12月 03 18:24:19 我的域名 trojan[13535]: Welcome to trojan 1.16.0
> 12月 03 18:24:19 我的域名 trojan[13535]: [2020-12-03 18:24:19] [FATAL] fatal: use_private_key_file: No such file or directory
> 12月 03 18:24:19 我的域名 trojan[13535]: [2020-12-03 18:24:19] [FATAL] exiting. . .
> 12月 03 18:24:19 我的域名 systemd[1]: trojan.service: Failed with result 'exit-code'.
> 12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Service RestartSec=1s expired, scheduling restart.
> 12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Scheduled restart job, restart counter is at 5.
> 12月 03 18:24:20 我的域名 systemd[1]: Stopped trojan.
> 12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Start request repeated too quickly.
> 12月 03 18:24:20 我的域名 systemd[1]: trojan.service: Failed with result 'exit-code'.
> 12月 03 18:24:20 我的域名 systemd[1]: Failed to start trojan.
> ```

你的问题解决了吗？我也存在这个情况
