### ISSUE TITLE
在证书到期了时候，没有自动续期

### ISSUE THREAD

**Issue by ricler** [johnrosen1/vpstoolbox#107]
**Is it really a bug?Please try to solve it by yourself first.（无论这是否是一个Bug,请先尝试自行解决！）**

**Non-related topics will be marked as spam and be closed immediately!（所有与本项目无关的话题都将被视为spam并被立即关闭！）**

**请勿使用Vultr运行本项目,vultr导致的一切错误,本项目不负责！！！**

**Describe the bug**
在证书到期了时候，没有自动续期
重新安装脚本，使用旧的配置，依旧没有续期

The [****] expiration date is : 2020-09-20 04:10:54 && [-1 days]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by johnrosen1** [comment]
@ricler 最新版已解决此问题，请覆盖安装，谢谢

**Comment by ricler** [comment]
> @ricler 最新版已解决此问题，请覆盖安装，谢谢

刚刚就是使用的最新版本，安装过程中，提示已有证书，跳过了。

也重新试了一遍，还是不行。

**Comment by johnrosen1** [comment]
@ricler 行吧，我修一下

**Comment by johnrosen1** [comment]
@ricler https://github.com/johnrosen1/vpstoolbox/commit/cf443c26613fd72f413f77c146a824e57bd0a6fe 可以了

**Comment by ricler** [comment]
> @ricler [cf443c2](https://github.com/johnrosen1/vpstoolbox/commit/cf443c26613fd72f413f77c146a824e57bd0a6fe) 可以了

我分别使用旧配置和新配置跑了一遍

旧的配置已经是0days

新的配置提示

```
[Mon 21 Sep 2020 10:10:05 AM HKT] Add '--force' to force to renew.
证书申请测试失败，请检查VPS控制面板防火墙(80 443)是否打开!!!
请访问https://letsencrypt.status.io/检测Let's encrypt服务是否正常!!!
Cert issue fail,Pleae Open port 80 443 on VPS panel !!!
```

我再跑一遍吧，不行只能重装系统了。

**Comment by johnrosen1** [comment]
https://github.com/johnrosen1/vpstoolbox/commit/f6a1d0b36ef1bea1e1bde00ac3ac3e405fa8831d 这样应该就行了

**Comment by ricler** [comment]
> [f6a1d0b](https://github.com/johnrosen1/vpstoolbox/commit/f6a1d0b36ef1bea1e1bde00ac3ac3e405fa8831d) 这样应该就行了

感谢，重新试了下，我觉得还是重装系统吧。

**Comment by ricler** [comment]
全新安装的证书还是到期了
expiration date is : 2020-09-21 00:00:00 && [0 days]

**Comment by johnrosen1** [comment]
@ricler 你访问网站试试

**Comment by johnrosen1** [comment]
closed
