### ISSUE TITLE
Script not working with vultr

### ISSUE THREAD

**Issue by rvpn** [johnrosen1/vpstoolbox#111]
I try to install the script on vultr but  it stucks here forever , using debian 10.
![vultr stuck](https://user-images.githubusercontent.com/28747439/103232648-fa0ba300-4975-11eb-9524-239e19c20e43.PNG)

But it works on upcloud.com or digital ocean with no problem.

**Comment by rvpn** [comment]
How to reproduce? 

Use vultr.com debian 10.

**Comment by johnrosen1** [comment]
vultr is shit , do not use it ,thanks.
