### ISSUE TITLE
tcp fast open error

### ISSUE THREAD

**Issue by rvpn** [johnrosen1/vpstoolbox#112]
[2020-12-29 01:46:20] [FATAL] fatal: /usr/local/etc/trojan/config.json(38): expected value

I removed line 38 and now its working again.

![trojan fix](https://user-images.githubusercontent.com/28747439/103233563-612a5700-4978-11eb-9a25-69b06b7e38f1.PNG)

**Comment by johnrosen1** [comment]
fixed
