### ISSUE TITLE
卸载功能

### ISSUE THREAD

**Issue by mulder125** [johnrosen1/vpstoolbox#116]
查无"卸载"或"uninstall"

### 这是一个什么样的功能？
完整或部份卸载vpstoolbox

### 这个功能可以解决什么问题？
想要卸载完整或部份卸载vpstoolbox在VPS

### 额外描述
记得以前是有卸载功能的，最近发现没有了

### 你觉得这个功能是否应该作为默认安装选项出现?
看能否加回此功能

**Comment by johnrosen1** [comment]
@mulder125 可以，问题不大

**Comment by johnrosen1** [comment]
已添加
