### ISSUE TITLE
证书失败

### ISSUE THREAD

**Issue by 2021-One** [johnrosen1/vpstoolbox#122]
正式证书申请ing(issuing) let\'s encrypt certificate
[四  8月 12 21:26:02 HKT 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[四  8月 12 21:26:02 HKT 2021] Single domain='xxxxxx'
[四  8月 12 21:26:02 HKT 2021] Getting domain auth token for each domain
[四  8月 12 21:26:05 HKT 2021] Getting webroot for domain='xxxxx'
[四  8月 12 21:26:05 HKT 2021] Verifying: xxxxx
[四  8月 12 21:26:05 HKT 2021] Nginx mode for domain:xxxxx
[四  8月 12 21:26:05 HKT 2021] Can not find conf file for domain xxxxx
[四  8月 12 21:26:05 HKT 2021] Please check log file for more details: /root/.acme.sh/acme.sh.log
证书申请失败，请**检查VPS控制面板防火墙是否完全关闭**,DNS是否解析完成!!!
请访问https://letsencrypt.status.io/检测Let's encrypt服务是否正常!!!
Cert issue fail,Pleae Open all ports on VPS panel !!!

**Comment by Martin-Yeh** [comment]
这个和防火墙没有关系， 已经关闭了防火墙。DNS也是正确的，但是到这一步还算是出现这样的问题。

**Comment by Martin-Yeh** [comment]
[四  8月 12 21:33:16 HKT 2021] default_acme_server
[四  8月 12 21:33:16 HKT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[四  8月 12 21:33:16 HKT 2021] It is recommended to install socat first.
[四  8月 12 21:33:16 HKT 2021] We use socat for standalone server if you use standalone mode.
[四  8月 12 21:33:16 HKT 2021] If you don't use standalone mode, just ignore this warning.
[四  8月 12 21:33:16 HKT 2021] Installing to /root/.acme.sh
[四  8月 12 21:33:16 HKT 2021] Installed to /root/.acme.sh/acme.sh
[四  8月 12 21:33:16 HKT 2021] Using config home:/root/.acme.sh
[四  8月 12 21:33:16 HKT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[四  8月 12 21:33:16 HKT 2021] Using sed  -i
[四  8月 12 21:33:16 HKT 2021] Found profile: /root/.bashrc
[四  8月 12 21:33:16 HKT 2021] Installing alias to '/root/.bashrc'
[四  8月 12 21:33:16 HKT 2021] OK, Close and reopen your terminal to start using acme.sh
[四  8月 12 21:33:16 HKT 2021] Using config home:/root/.acme.sh
[四  8月 12 21:33:16 HKT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[四  8月 12 21:33:16 HKT 2021] Installing cron job
[四  8月 12 21:33:16 HKT 2021] Good, bash is found, so change the shebang to use bash as preferred.
[四  8月 12 21:33:17 HKT 2021] OK
[四  8月 12 21:33:17 HKT 2021] default_acme_server
[四  8月 12 21:33:17 HKT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[四  8月 12 21:33:17 HKT 2021] Retrying GET
[四  8月 12 21:33:17 HKT 2021] GET
[四  8月 12 21:33:17 HKT 2021] url='https://api.github.com/repos/acmesh-official/acme.sh/git/refs/heads/master'
[四  8月 12 21:33:17 HKT 2021] timeout=
[四  8月 12 21:33:17 HKT 2021] displayError='1'
[四  8月 12 21:33:17 HKT 2021] _CURL='curl --silent --dump-header /tmp/tmp.xSnYTvi0sY  -L  -g '
[四  8月 12 21:33:17 HKT 2021] ret='0'
[四  8月 12 21:33:17 HKT 2021] _hcode='0'
[四  8月 12 21:33:17 HKT 2021] Running cmd: upgrade
[四  8月 12 21:33:17 HKT 2021] Using config home:/root/.acme.sh
[四  8月 12 21:33:17 HKT 2021] default_acme_server
[四  8月 12 21:33:17 HKT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[四  8月 12 21:33:17 HKT 2021] Retrying GET
[四  8月 12 21:33:17 HKT 2021] GET
[四  8月 12 21:33:17 HKT 2021] url='https://api.github.com/repos/acmesh-official/acme.sh/git/refs/heads/master'
[四  8月 12 21:33:17 HKT 2021] timeout=
[四  8月 12 21:33:17 HKT 2021] displayError='1'
[四  8月 12 21:33:17 HKT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[四  8月 12 21:33:17 HKT 2021] ret='0'
[四  8月 12 21:33:17 HKT 2021] _hcode='0'
[四  8月 12 21:33:17 HKT 2021] Already uptodate!
[四  8月 12 21:33:17 HKT 2021] Upgrade success!
[四  8月 12 21:33:17 HKT 2021] Running cmd: issue
[四  8月 12 21:33:17 HKT 2021] _main_domain='v.name.com'
[四  8月 12 21:33:17 HKT 2021] _alt_domains='no'
[四  8月 12 21:33:17 HKT 2021] Using config home:/root/.acme.sh
[四  8月 12 21:33:17 HKT 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[四  8月 12 21:33:17 HKT 2021] DOMAIN_PATH='/etc/certs/v.name.com_ecc'
[四  8月 12 21:33:17 HKT 2021] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[四  8月 12 21:33:17 HKT 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[四  8月 12 21:33:17 HKT 2021] Retrying GET
[四  8月 12 21:33:17 HKT 2021] GET
[四  8月 12 21:33:17 HKT 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[四  8月 12 21:33:17 HKT 2021] timeout=
[四  8月 12 21:33:17 HKT 2021] displayError='1'
[四  8月 12 21:33:17 HKT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[四  8月 12 21:33:18 HKT 2021] ret='0'
[四  8月 12 21:33:18 HKT 2021] _hcode='0'
[四  8月 12 21:33:18 HKT 2021] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[四  8月 12 21:33:18 HKT 2021] ACME_NEW_AUTHZ
[四  8月 12 21:33:18 HKT 2021] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[四  8月 12 21:33:18 HKT 2021] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[四  8月 12 21:33:18 HKT 2021] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[四  8月 12 21:33:18 HKT 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[四  8月 12 21:33:18 HKT 2021] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[四  8月 12 21:33:18 HKT 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[四  8月 12 21:33:18 HKT 2021] _on_before_issue
[四  8月 12 21:33:18 HKT 2021] _chk_main_domain='v.name.com'
[四  8月 12 21:33:18 HKT 2021] _chk_alt_domains
[四  8月 12 21:33:18 HKT 2021] Le_LocalAddress
[四  8月 12 21:33:18 HKT 2021] d='v.name.com'
[四  8月 12 21:33:18 HKT 2021] Check for domain='v.name.com'
[四  8月 12 21:33:18 HKT 2021] _currentRoot='nginx:'
[四  8月 12 21:33:18 HKT 2021] d
[四  8月 12 21:33:18 HKT 2021] _saved_account_key_hash is not changed, skip register account.
[四  8月 12 21:33:18 HKT 2021] Read key length:
[四  8月 12 21:33:18 HKT 2021] Creating domain key
[四  8月 12 21:33:18 HKT 2021] Using config home:/root/.acme.sh
[四  8月 12 21:33:18 HKT 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[四  8月 12 21:33:18 HKT 2021] Use length 256
[四  8月 12 21:33:18 HKT 2021] Using ec name: prime256v1
[四  8月 12 21:33:18 HKT 2021] The domain key is here: /etc/certs/v.name.com_ecc/v.name.com.key
[四  8月 12 21:33:18 HKT 2021] _createcsr
[四  8月 12 21:33:18 HKT 2021] Single domain='v.name.com'
[四  8月 12 21:33:18 HKT 2021] Getting domain auth token for each domain
[四  8月 12 21:33:18 HKT 2021] d
[四  8月 12 21:33:18 HKT 2021] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[四  8月 12 21:33:18 HKT 2021] payload='{"identifiers": [{"type":"dns","value":"v.name.com"}]}'
[四  8月 12 21:33:18 HKT 2021] RSA key
[四  8月 12 21:33:18 HKT 2021] Retrying post
[四  8月 12 21:33:18 HKT 2021] HEAD
[四  8月 12 21:33:18 HKT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[四  8月 12 21:33:19 HKT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g  -I  '
[四  8月 12 21:33:19 HKT 2021] _ret='0'
[四  8月 12 21:33:19 HKT 2021] _hcode='0'
[四  8月 12 21:33:19 HKT 2021] Retrying post
[四  8月 12 21:33:19 HKT 2021] POST
[四  8月 12 21:33:19 HKT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[四  8月 12 21:33:19 HKT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[四  8月 12 21:33:20 HKT 2021] _ret='0'
[四  8月 12 21:33:20 HKT 2021] _hcode='0'
[四  8月 12 21:33:20 HKT 2021] code='201'
[四  8月 12 21:33:20 HKT 2021] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/157509081/16376010060'
[四  8月 12 21:33:20 HKT 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/157509081/16376010060'
[四  8月 12 21:33:20 HKT 2021] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/21209461780'
[四  8月 12 21:33:20 HKT 2021] payload
[四  8月 12 21:33:21 HKT 2021] Retrying post
[四  8月 12 21:33:21 HKT 2021] POST
[四  8月 12 21:33:21 HKT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/21209461780'
[四  8月 12 21:33:21 HKT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[四  8月 12 21:33:21 HKT 2021] _ret='0'
[四  8月 12 21:33:21 HKT 2021] _hcode='0'
[四  8月 12 21:33:21 HKT 2021] code='200'
[四  8月 12 21:33:21 HKT 2021] d='v.name.com'
[四  8月 12 21:33:21 HKT 2021] Getting webroot for domain='v.name.com'
[四  8月 12 21:33:21 HKT 2021] _w='nginx:'
[四  8月 12 21:33:21 HKT 2021] _currentRoot='nginx:'
[四  8月 12 21:33:21 HKT 2021] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/21209461780/IZ-XVw","token":"wShCZFHYM-3YBTWdpisLFlWbz4mF8djIiQR-29vnkeI"'
[四  8月 12 21:33:21 HKT 2021] token='wShCZFHYM-3YBTWdpisLFlWbz4mF8djIiQR-29vnkeI'
[四  8月 12 21:33:22 HKT 2021] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/21209461780/IZ-XVw'
[四  8月 12 21:33:22 HKT 2021] keyauthorization='wShCZFHYM-3YBTWdpisLFlWbz4mF8djIiQR-29vnkeI.LA9wncU6AJHlEETceEI5gXnD14CdL0ab1H519gfFyw8'
[四  8月 12 21:33:22 HKT 2021] dvlist='v.name.com#wShCZFHYM-3YBTWdpisLFlWbz4mF8djIiQR-29vnkeI.LA9wncU6AJHlEETceEI5gXnD14CdL0ab1H519gfFyw8#https://acme-v02.api.letsencrypt.org/acme/chall-v3/21209461780/IZ-XVw#http-01#nginx:'
[四  8月 12 21:33:22 HKT 2021] d
[四  8月 12 21:33:22 HKT 2021] vlist='v.name.com#wShCZFHYM-3YBTWdpisLFlWbz4mF8djIiQR-29vnkeI.LA9wncU6AJHlEETceEI5gXnD14CdL0ab1H519gfFyw8#https://acme-v02.api.letsencrypt.org/acme/chall-v3/21209461780/IZ-XVw#http-01#nginx:,'
[四  8月 12 21:33:22 HKT 2021] d='v.name.com'
[四  8月 12 21:33:22 HKT 2021] ok, let's start to verify
[四  8月 12 21:33:22 HKT 2021] Verifying: v.name.com
[四  8月 12 21:33:22 HKT 2021] d='v.name.com'
[四  8月 12 21:33:22 HKT 2021] keyauthorization='wShCZFHYM-3YBTWdpisLFlWbz4mF8djIiQR-29vnkeI.LA9wncU6AJHlEETceEI5gXnD14CdL0ab1H519gfFyw8'
[四  8月 12 21:33:22 HKT 2021] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/21209461780/IZ-XVw'
[四  8月 12 21:33:22 HKT 2021] _currentRoot='nginx:'
[四  8月 12 21:33:22 HKT 2021] Nginx mode for domain:v.name.com
[四  8月 12 21:33:22 HKT 2021] _croot='nginx:'
[四  8月 12 21:33:22 HKT 2021] _start_f
[四  8月 12 21:33:22 HKT 2021] find start conf from nginx command
[四  8月 12 21:33:22 HKT 2021] NGINX_CONF='--conf-path=/etc/nginx/nginx.conf'
[四  8月 12 21:33:22 HKT 2021] NGINX_CONF='/etc/nginx/nginx.conf'
[四  8月 12 21:33:22 HKT 2021] Found nginx conf file:/etc/nginx/nginx.conf
[四  8月 12 21:33:22 HKT 2021] Start detect nginx conf for v.name.com from:/etc/nginx/nginx.conf
[四  8月 12 21:33:22 HKT 2021] Start _checkConf from:/etc/nginx/nginx.conf
[四  8月 12 21:33:22 HKT 2021] single
[四  8月 12 21:33:22 HKT 2021] _isRealNginxConf v.name.com /etc/nginx/nginx.conf
[四  8月 12 21:33:22 HKT 2021] Can not find conf file for domain v.name.com
[四  8月 12 21:33:22 HKT 2021] pid
[四  8月 12 21:33:22 HKT 2021] No need to restore nginx, skip.
[四  8月 12 21:33:22 HKT 2021] _clearupdns
[四  8月 12 21:33:22 HKT 2021] dns_entries
[四  8月 12 21:33:22 HKT 2021] skip dns.
[四  8月 12 21:33:22 HKT 2021] _on_issue_err
[四  8月 12 21:33:22 HKT 2021] Please check log file for more details: /root/.acme.sh/acme.sh.log
[四  8月 12 21:33:22 HKT 2021] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/21209461780/IZ-XVw'
[四  8月 12 21:33:22 HKT 2021] payload='{}'
[四  8月 12 21:33:22 HKT 2021] Retrying post
[四  8月 12 21:33:22 HKT 2021] POST
[四  8月 12 21:33:22 HKT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/21209461780/IZ-XVw'
[四  8月 12 21:33:22 HKT 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[四  8月 12 21:33:23 HKT 2021] _ret='0'
[四  8月 12 21:33:23 HKT 2021] _hcode='0'
[四  8月 12 21:33:23 HKT 2021] code='200'

**Comment by Ros-ua** [comment]
![image](https://user-images.githubusercontent.com/51153745/129359664-f8761175-aefa-4674-8d46-8d3507093831.png)

**Comment by johnrosen1** [comment]
@2021-One 看起来是acme.sh改变了nginx配置检测方法，我去再看看。

**Comment by Ros-ua** [comment]
instead of https just use 2 option with DNS API. worked for me with Cloudflare

**Comment by johnrosen1** [comment]
@2021-One 我根据他们的wiki改成了最新的命令，你自己试试，可以的话就关掉issue即可。

**Comment by 2021-One** [comment]
> @2021-One 我根据他们的wiki改成了最新的命令，你自己试试，可以的话就关掉issue即可。

已经OK @johnrosen1

**Comment by johnrosen1** [comment]
solved.

**Comment by 2021-One** [comment]
[2022年 03月 09日 星期三 11:38:51 UTC] Running cmd: issue
[2022年 03月 09日 星期三 11:38:51 UTC] _main_domain='xxx.xxx.xxx'
[2022年 03月 09日 星期三 11:38:51 UTC] _alt_domains='no'
[2022年 03月 09日 星期三 11:38:51 UTC] Using config home:/root/.acme.sh
[2022年 03月 09日 星期三 11:38:51 UTC] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[2022年 03月 09日 星期三 11:38:51 UTC] DOMAIN_PATH='/etc/certs/xxx.xxx.xxx_ecc'
[2022年 03月 09日 星期三 11:38:51 UTC] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[2022年 03月 09日 星期三 11:38:51 UTC] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[2022年 03月 09日 星期三 11:38:51 UTC] GET
[2022年 03月 09日 星期三 11:38:51 UTC] url='https://acme-v02.api.letsencrypt.org/directory'
[2022年 03月 09日 星期三 11:38:51 UTC] timeout=
[2022年 03月 09日 星期三 11:38:51 UTC] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[2022年 03月 09日 星期三 11:38:52 UTC] ret='0'
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_NEW_AUTHZ
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-201
7.pdf'
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[2022年 03月 09日 星期三 11:38:52 UTC] Using CA: https://acme-v02.api.letsencrypt.org/directory
[2022年 03月 09日 星期三 11:38:52 UTC] _on_before_issue
[2022年 03月 09日 星期三 11:38:52 UTC] _chk_main_domain='xxx.xxx.xxx'
[2022年 03月 09日 星期三 11:38:52 UTC] _chk_alt_domains
[2022年 03月 09日 星期三 11:38:52 UTC] Le_LocalAddress
[2022年 03月 09日 星期三 11:38:52 UTC] d='xxx.xxx.xxx'
[2022年 03月 09日 星期三 11:38:52 UTC] Check for domain='xxx.xxx.xxx'
[2022年 03月 09日 星期三 11:38:52 UTC] _currentRoot='nginx:/etc/nginx/conf.d/default.conf'
[2022年 03月 09日 星期三 11:38:52 UTC] d
[2022年 03月 09日 星期三 11:38:52 UTC] config file is empty, can not read CA_KEY_HASH
[2022年 03月 09日 星期三 11:38:52 UTC] Using config home:/root/.acme.sh
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[2022年 03月 09日 星期三 11:38:52 UTC] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[2022年 03月 09日 星期三 11:38:52 UTC] Use default length 2048
[2022年 03月 09日 星期三 11:38:52 UTC] length='2048'
[2022年 03月 09日 星期三 11:38:52 UTC] Using config home:/root/.acme.sh
[2022年 03月 09日 星期三 11:38:52 UTC] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[2022年 03月 09日 星期三 11:38:52 UTC] Use length 2048
[2022年 03月 09日 星期三 11:38:52 UTC] Using RSA: 2048
[2022年 03月 09日 星期三 11:38:52 UTC] Create account key ok.
[2022年 03月 09日 星期三 11:38:52 UTC] RSA key
[2022年 03月 09日 星期三 11:38:52 UTC] config file is empty, can not read CA_EAB_KEY_ID
[2022年 03月 09日 星期三 11:38:52 UTC] config file is empty, can not read CA_EAB_HMAC_KEY
[2022年 03月 09日 星期三 11:38:52 UTC] config file is empty, can not read CA_EMAIL
[2022年 03月 09日 星期三 11:38:52 UTC] Registering account: https://acme-v02.api.letsencrypt.org/directory
[2022年 03月 09日 星期三 11:38:52 UTC] url='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[2022年 03月 09日 星期三 11:38:52 UTC] payload='{"termsOfServiceAgreed": true}'
[2022年 03月 09日 星期三 11:38:52 UTC] HEAD
[2022年 03月 09日 星期三 11:38:52 UTC] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'



@johnrosen1
