### ISSUE TITLE
rss服务无法安装

### ISSUE THREAD

**Issue by jayzhou14** [johnrosen1/vpstoolbox#129]
安装rss服务后，按照面板地址访问显示502，用docker ps查询发现没装上，手动docker-compose up -d安装提示redis出错，查询redis状态好像是正常的，Debian9-11都测试过了。

**root:/usr/share/nginx/miniflux# docker-compose up -d**
service "rsshub" depends on undefined service redis: invalid compose project

**root:/usr/share/nginx/miniflux# ps aux | grep redis-server**
redis        598    0.3  1.0   58840 10420 ?        Ssl   Aug19   3:00 /usr/bin/redis-server 127.0.0.1:6379
root       25057  0.0  0.0   5136   664 pts/0     S+   11:15     0:00 grep redis-server

**root:/usr/share/nginx/miniflux# lsof  -i:6379**
COMMAND   PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
redis-ser 598 redis    6u  IPv4  11855      0t0  TCP localhost:redis (LISTEN)
redis-ser 598 redis    7u  IPv6  11856      0t0  TCP localhost:redis (LISTEN)

**root:/usr/share/nginx/miniflux# netstat -tunpl | grep 6379** 
tcp        0      0 127.0.0.1:6379          0.0.0.0:*           LISTEN      598/redis-server 12 
tcp6      0      0 ::1:6379                     :::*                    LISTEN      598/redis-server 12

**Comment by johnrosen1** [comment]
@jayzhou14 你看一眼最新的 commit 改一下 yml 文件再试试

**Comment by jayzhou14** [comment]
> @jayzhou14 你看一眼最新的 commit 改一下 yml 文件再试试

改了127.0.0.1再次docker-compose up -d依然是同样的错误

**Comment by johnrosen1** [comment]
@jayzhou14 网络模式改成 host 试试

**Comment by jayzhou14** [comment]
> @jayzhou14 网络模式改成 host 试试

看了commit改了network_mode: host还是没用，对比官方的[docker-compose.yml](https://github.com/DIYgod/RSSHub/blob/master/docker-compose.yml)，redis装在docker里的，不太懂编程不知是否跟这个有关

**Comment by johnrosen1** [comment]
@jayzhou14 systemctl disable redis —now

**Comment by johnrosen1** [comment]
我删掉了外装的 redis , 你再试试

**Comment by jayzhou14** [comment]
> 我删掉了外装的 redis , 你再试试

redis按照官方，放在browserless后面跟它同级，加上volumes: redis-data:，miniflux维持之前的不要改。但运行时会在安装两段代码之间那行报错，我将rsshub和miniflux分成两个yml分别安装，终于成功了。
![Snipaste_2022-08-20_17-07-04](https://user-images.githubusercontent.com/59425407/185738168-ae65dc11-5b25-491a-8470-b1867dccda55.png)
