### ISSUE TITLE
几个改进建议

### ISSUE THREAD

**Issue by gztingting** [johnrosen1/vpstoolbox#50]
1、测试需要，有时候需要反复卸载与安装，建议也增加一键卸载功能，把所有文件清理掉。
2、目前我卸载后重新运行一键安装脚本，到域名解析这一步进行不下去，动手能力不强的网友估计无法解决。究其原因是前一次一键安装时选择了将VPS本机hostname设置成了自己的域名，因此脚本解析返回的ip地址是127.0.0.1 localhost，而不是外网ipv4地址，所以脚本自动停止。建议脚本改进为用外部DNS的数据，或者清空本机域名指向localhost，或者不要取消将本机hostname改名的设置。
3、配置信息json文件以及html文件存在泄漏风险，建议一个小时候自动删除。
4、SSH vps后自动显示的信息是永久性，建议可以提供不显示的选型。

**Comment by johnrosen1** [comment]
@gztingting 问题2已解决，其余问题请自行解决
