### ISSUE TITLE
Web Panel to add more users

### ISSUE THREAD

**Issue by xenstar** [johnrosen1/vpstoolbox#68]
**Is your feature request related to a problem? Please describe.**

Actually I wanted to change the password or give new access to my girlfriend but there's no panel for it. 

**Describe the solution you'd like**
I saw there are some web panel for Trojan. If you can add it in your code, we can install the panel on our server too.

**Comment by johnrosen1** [comment]
@xenstar no such plan for now,pull request  welcome

**Comment by xenstar** [comment]
I saw there are some panel script codes actually, but the problem is they want to have a clean install. So if I do a clean install, this vpstoolbox I have to remove which I don't want. VPStoolbox is great.

https://www.v2rayssr.com/trojan-panel-aoto.html
https://trojan-tutor.github.io/2019/06/08/p43.html
https://www.v2rayssr.com/trojan-panel.html

Also do you have any telegram group? I have joined the channel already.
