### ISSUE TITLE
现在不支持CentOS了吗

### ISSUE THREAD

**Issue by wuseal** [johnrosen1/vpstoolbox#82]
我之前使用安装的时候是支持的呀,现在只支持ubuntu和debian了吗

**Comment by johnrosen1** [comment]
@wuseal 由於支援centos過於麻煩且無必要，故移除，若為剛需，請自行pr

**Comment by wuseal** [comment]
> @wuseal 由於支援centos過於麻煩且無必要，故移除，若為剛需，請自行pr

好的，感谢
