### ISSUE TITLE
Trojan panel

### ISSUE THREAD

**Issue by hybtoy** [johnrosen1/vpstoolbox#85]
Hello. Can somebody please explain me, which password  I have to input in inginter for Android after user creation?
Let's say, I have created testuser with email test@user.com and password testuserpassword. So what will be the password for Igniter and windows app?

**Comment by johnrosen1** [comment]
@hybtoy username:password email does not matter

**Comment by hybtoy** [comment]
@johnrosen1 
Thanks. Closed.

**Comment by hybtoy** [comment]
@johnrosen1 
Any plans to use [this panel](https://github.com/Jrohy/trojan) instead of official one? 
Thanks.

**Comment by johnrosen1** [comment]
please open a pr by yourself

**Comment by hybtoy** [comment]
> please open a pr by yourself

Unfortunately, I am not coder. I don't know shell.

**Comment by johnrosen1** [comment]
@hybtoy then i can not help you,sorry
