### ISSUE TITLE
Can‘t uninstall this vpstoolbox completely

### ISSUE THREAD

**Issue by zhikang-ye** [johnrosen1/vpstoolbox#89]
It seems that the vps.sh successfully uninstall trojan. But after the installation, I can still not resolve a domain. Like" ping: google.com: Temporary failure in name resolution". I tried several ways like changing resolve.conf, netplan or something, but all failed. Could you please tell me how to solve this problem?

**Comment by johnrosen1** [comment]
@zhikang-ye ok,i will fix it

**Comment by johnrosen1** [comment]
fixed
